/*
ls          = Lista arquivos e pastas no diretório atual
cd <diretório> = Muda para o diretório especificado
cd ..       = Volta um nível no diretório
cd -        = Volta para o diretório anterior
cd /        = Volta para o diretório raiz
cd ~        = Volta para o diretório home do usuário
pwd         = Mostra o caminho completo do diretório atual
mkdir       = Cria um novo diretório
touch       = Cria um novo arquivo vazio
rm          = Remove arquivos ou diretórios (cuidado!)
rm -r       = Remove diretórios e seus conteúdos
rm -rf      = Remove diretórios e seus conteúdos de forma recursiva e forçada (cuidado!)
rmdir       = Remove diretórios vazios
mv <origem> <destino> = Move um arquivo ou diretório
mv <nome_antigo> <nome_novo> = Renoeia um arquivo ou diretório
nano        = Abre o editor de texto Nano
vim         = Abre o editor de texto Vim
cat         = Mostra o conteúdo de um arquivo
cp          = Copia arquivos ou diretórios
cp <origem> <destino> = Copia um arquivo ou diretório
cp -r       = Copia diretórios de forma recursiva
rm -rf      = Remove arquivos ou diretórios de forma recursiva e forçada (cuidado!)
git clone <link>  = Clona um repositório remoto para sua máquina local
git add     = Adiciona arquivos ao staging do Git (prepara para commit)
git commit  = Salva as alterações no histórico do Git
git commit -m "<mensagem>" = Salva as alterações com uma mensagem descritiva
git push    = Envia os commits locais para o repositório remoto
git pull    = Atualiza o repositório local com as alterações do remoto
git status  = Mostra o status do repositório (arquivos modificados, não rastreados, etc.)
git log     = Mostra o histórico de commits
git log --oneline = Mostra o histórico de commits em uma linha
git diff    = Mostra as diferenças entre o repositório local e o remoto
git diff <commit1> <commit2> = Mostra as diferenças entre dois commits
git config --global user.name "<seu-nome>" = Configura o nome do usuário
git config --global user.email "<seu-email>" = Configura o e-mail do usuário
git config --global core.editor "<editor>" = Configura o editor padrão do Git
git config --global alias.<alias> "<comando>" = Cria um atalho para um comando do Git
git config --global --list = Lista todas as configurações do Git
git init    = Inicializa um novo repositório Git
git branch  = Lista todas as branches do repositório
git branch <nome-da-branch> = Cria uma nova branch
git branch -m <nome-da-branch> = Renomeia a branch atual
git branch -m <nome-antigo> <nome-novo> = Renomeia uma branch
git branch -a = Lista todas as branches (locais e remotas)
git branch -r = Lista apenas as branches remotas
git branch -d <nome-da-branch>  = Remove uma branch local (se já foi mesclada)
git branch -D <nome-da-branch>  = Força a remoção de uma branch local
git checkout <hash_do_commit> = Muda para um commit específico
git checkout <nome-da-branch> = Muda para uma branch específica
git checkout -b <nome-da-branch> = Cria e muda para uma nova branch
git revert <hash_do_commit> = Cria um commit que desfaz as alterações de um commit anterior
git reset <hash_do_commit> = Desfaz os commits até o commit especificado
git reset --hard <hash_do_commit> = Desfaz os commits e as alterações no diretório de trabalho
git push origin --delete = Remove uma branch do repositório remoto
git merge <nome-da-branch> = Mescla uma branch com a branch atual
code .      = Abre o diretório atual no Visual Studio Code
code <arquivo> = Abre um arquivo específico no Visual Studio Code
*/
